### ISSUE TITLE
What about Kokojima's method?

### ISSUE THREAD

**Issue by prepare** [JoaoBaptMG/PathRenderingLab#1]
Hello @JoaoBaptMG.

I don't hesitate to subscribe as the Lab's fanclub :)
 
I love your works! :+1: :1st_place_medal: 

What about Kokojima's method
_"Resolution Indendent Rendering of Deformable Vector Objects using Graphics Hardware"_

They use Stencil+ Loop-Blinn, But they said it is more simpler than only Loop-Blinn.
 
[p118-kokojima.pdf](https://github.com/JoaoBaptMG/PathRenderingLab/files/2834247/p118-kokojima.1.pdf)

**Comment by JoaoBaptMG** [comment]
Hey @prepare, I have seen this method too, while searching for alternatives of Loop-Blinn. However, it requires a stencil buffer (it uses it to compute pixel coverage, according to the fill rules), and is also not easy to antialias with quality - the method chosen can antialias the curve on the pixel shader, this one would not be possible by the very nature of the stencil buffer.

Edit: sorry for the lateness, for some reason GitHub did not alert me of the issue.
